
'use client';

import { QuizClient } from '@/components/quiz-client';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { FileText } from 'lucide-react';
import {
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription
} from '@/components/ui/dialog';
import type { QuizQuestion } from '@/lib/data/mock-test-data';

export function AiWeeklyTestClient({ quizData }: { quizData: QuizQuestion[] }) {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <FileText className="h-5 w-5 text-primary" />
          Weekly Mock Test
        </CardTitle>
        <CardDescription>
          A full-length mock test, generated by AI, to challenge you every week.
        </CardDescription>
      </CardHeader>
      <CardContent className="flex flex-col items-center justify-center text-center p-8">
        <p className="text-lg font-semibold mb-2">Ready to test your knowledge?</p>
        <p className="text-muted-foreground mb-4">This is a timed test with {quizData.length} questions.</p>
        <Dialog>
          <DialogTrigger asChild>
            <Button size="lg">Start Weekly Test</Button>
          </DialogTrigger>
          <DialogContent className="max-w-6xl h-[90vh] flex flex-col">
            <DialogHeader>
              <DialogTitle>AI Weekly Mock Test</DialogTitle>
              <DialogDescription>
                Good luck! You have 120 minutes to complete this test.
              </DialogDescription>
            </DialogHeader>
            <div className="flex-grow overflow-y-auto -mx-6 px-2">
              <QuizClient quizData={quizData} isMockTest={true} />
            </div>
          </DialogContent>
        </Dialog>
      </CardContent>
    </Card>
  );
}
